### ISSUE TITLE
Package euca-deploy for RPM based distros

### ISSUE THREAD

**Issue by viglesiasce** [viglesiasce/euca-deploy#29]
We need to be able to install euca-deploy and its dependencies via yum. 

Currently the dependencies are:
### Unpackaged python libraries
- Fabric (this drags in paramiko which is a problem on CentOS 6 afaik because of pycrypto needing to be newer, [current packaging on koji](http://koji.fedoraproject.org/koji/packageinfo?packageID=8140).
### Packages
- PyYaml
- python-devel 
- gcc 
- git 
- python-setuptools

**Comment by viglesiasce** [comment]
I started some work on this a while back:
https://bintray.com/viglesiasce/euca-deploy

I never got it to work fully due to the pycrypto issues mentioned above.

**Comment by viglesiasce** [comment]
The error from paramiko:

``` bash
[root@h-32 ~]# euca-deploy
Traceback (most recent call last):
  File "/usr/bin/euca-deploy", line 5, in <module>
    from eucadeploy.componentdeployer import ComponentDeployer
  File "/usr/lib/python2.6/site-packages/eucadeploy/componentdeployer.py", line 7, in <module>
    from eucadeploy.chefmanager import ChefManager
  File "/usr/lib/python2.6/site-packages/eucadeploy/chefmanager.py", line 7, in <module>
    from fabric.api import *
  File "/usr/lib/python2.6/site-packages/fabric/api.py", line 11, in <module>
    from fabric.decorators import (hosts, roles, runs_once, with_settings, task,
  File "/usr/lib/python2.6/site-packages/fabric/decorators.py", line 9, in <module>
    from Crypto import Random
ImportError: cannot import name Random
[root@h-32 ~]#
```

**Comment by viglesiasce** [comment]
@mbacchi 

Nice work on the packages from http://jenkins.release.eucalyptus-systems.com/job/p1-eucadeploy-build-devel-s03-rpm/4/. 

A few more tweaks are needed:

1) We need to depend on git as its used in some places
2) Can you install the config.yml in /etc/euca-deploy/config.yml? Ill then tweak the code to look there when I am fixing #36 

Other than those issues we are solid! Once again nice work!

**Comment by viglesiasce** [comment]
@mbacchi  I just thought of another impending dep from the plugins branch `python-stevedore`:
https://admin.fedoraproject.org/pkgdb/package/python-stevedore/

Its already available in epel thankfully.

**Comment by mbacchi** [comment]
@viglesiasce I could use your input on a couple questions:
1. Is config.yml intended to be a proper RPM 'config file' in the way that we wouldn't want to remove it when the RPM is removed?  Also when the package is upgraded it won't be overwritten due to the assumption users have modified it.
2. I think you are asking for python-stevedore to be required as an RPM Requires: entry vs. a pip install, is that correct?  I have installed it manually using pip on my test machine but I think this requirement would mean yum needs to install it for us via epel.

Thanks.
-Matt

**Comment by viglesiasce** [comment]
@mbacchi 

1) Users wont be tweaking this file much as far as I can tell. We do however need it to run. In an ideal world I'd like the following: we put it in place, then overwrite it on upgrade and save the previous one as a backup if its been changed. IIRC, there is a way in packaging to have it save the backup as *.rpmsave. Unfortunately I'm not savvy enough to know what that is.

2) Correct this is a package dependency.

**Comment by mbacchi** [comment]
From a very quick search I see that the %config directive automatically creates a .rpmsave file if the config file has been changed by the user, and is different than the file in the update RPM[1](https://www.suse.com/documentation/sles10/book_sle_reference/data/sec_rpm_pakete_verwalten.html), [2](http://www-uxsup.csx.cam.ac.uk/~jw35/docs/rpm_config.html).  If it hasn't changed from the old RPM version, it is simply overwritten.  That seems to be the behavior you are looking for.  What I don't know is how this is handled on removal, whether the config file is left around indefinitely.

I can do some testing to see if we can get a good understanding of how it works in practice.

**Comment by mbacchi** [comment]
@viglesiasce try the package here, I added the dependencies and the config.yml, and tested that it won't be overwritten during an upgrade.

http://jenkins.release.eucalyptus-systems.com/job/p1-eucadeploy-build-devel-s03-rpm/6/

**Comment by mbacchi** [comment]
@viglesiasce this package now includes the examples directory:

http://jenkins.release.eucalyptus-systems.com/job/p1-eucadeploy-build-devel-s03-rpm/7/artifact/results/euca-deploy-0.1-1.noarch.rpm

Let me know what you think.

**Comment by viglesiasce** [comment]
@mbacchi example envs look great. 

Still on the plate:
- Put in place /etc/euca-deploy/config.yml
- Have euca-deploy check ./etc/config.yml then /etc/euca-deploy/config.yml
